FROM java:8-jdk-alpine
MAINTAINER Rodrigue Tchuensu P. <pouopse@yahoo.fr>

WORKDIR /app

COPY spring-boot-server-0.0.1-SNAPSHOT.jar /app/spring-boot-server-0.0.1-SNAPSHOT.jar

EXPOSE 8090

CMD ["java", "-jar", "spring-boot-server-0.0.1-SNAPSHOT.jar"]